namespace A18.Realtime.Api;

internal static class SimpleOperationUi
{
    public const string Html = """
<!doctype html>
<html lang="zh-Hant">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>A18_2 精簡操作</title>
<style>
:root{color-scheme:dark;--bg:#0b111b;--panel:#121c2a;--line:#27364b;--text:#dbe7f5;--muted:#8191a8;--accent:#54a8ff;--ok:#72e6b6;--warn:#ffc857;--bad:#ff8993}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 system-ui,"Microsoft JhengHei",sans-serif}
header{padding:12px 18px;border-bottom:1px solid var(--line);background:#0f1825}.brand{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.brand h1{margin:0;font-size:17px}.tabs{display:flex;gap:4px;align-items:center}.tabs a{display:inline-block;padding:7px 11px;border:1px solid var(--line);border-radius:6px;text-decoration:none;color:var(--muted);background:#0b1420}.tabs a.active{color:#fff;border-color:#2787d5;background:#1769aa}
.content{max-width:1120px;margin:auto;padding:18px}.card{border:1px solid var(--line);background:var(--panel);border-radius:10px;overflow:hidden}.card-head{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:12px 14px;background:#172336;border-bottom:1px solid var(--line)}.card-head h2{margin:0 auto 0 0;font-size:16px}.badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#36404d;color:#dce7f5;font-size:11px}.ok{background:#174c38;color:#8df0be}.warn{background:#634915;color:#ffe19a}.bad{background:#682b33;color:#ffb3ba}
.form{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:12px;padding:14px}.field{grid-column:span 3;display:flex;flex-direction:column;gap:5px;min-width:0}.field.wide{grid-column:span 6}.field.full{grid-column:1/-1}.field label,.group-title{color:var(--muted);font-size:12px}.field input,.field select{width:100%;border:1px solid var(--line);border-radius:6px;background:#0b1420;color:var(--text);padding:9px 10px;font:inherit}.symbol-wrap{display:flex;gap:8px;align-items:center}.symbol-wrap input{flex:1}.company{min-width:100px;color:var(--text);font-size:13px}
.button-group{display:flex;gap:5px;flex-wrap:wrap}.toggle-btn{margin:0;border:1px solid var(--line);border-radius:7px;background:#0b1420;color:#aebed1;padding:9px 12px;cursor:pointer;font-weight:700;min-height:40px}.toggle-btn.active{background:#1769aa;border-color:#2d95e6;color:#fff}.direction .toggle-btn{flex:1}.direction .toggle-btn[data-value=SHORT].active{background:#8b3e57;border-color:#c85b7c}.toggle-btn:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
.switch-row{display:flex;align-items:center;gap:9px;min-height:41px}.switch{position:relative;width:42px;height:24px;display:inline-block}.switch input{display:none}.slider{position:absolute;inset:0;border-radius:15px;background:#33445a;cursor:pointer}.slider:after{content:"";position:absolute;width:20px;height:20px;left:2px;top:2px;border-radius:50%;background:#fff;transition:.18s}.switch input:checked+.slider{background:#178bd4}.switch input:checked+.slider:after{transform:translateX(18px)}
details{grid-column:1/-1;border:1px solid var(--line);border-radius:8px;background:#0e1825}details>summary{padding:10px 12px;cursor:pointer;color:#cfe2f7;font-weight:800}.advanced{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;padding:0 12px 12px}.advanced .field{grid-column:auto}
.status{grid-column:1/-1;padding:10px 12px;border:1px solid var(--line);border-radius:7px;background:#0b1420;color:var(--muted);min-height:43px}.status.ready{color:var(--ok);border-color:#285b48}.status.blocked{color:var(--bad);border-color:#6b3540}.actions{grid-column:1/-1;display:flex;gap:10px;align-items:center}.send{margin-left:auto;min-width:180px;border:1px solid #c58b24;border-radius:8px;background:#a86210;color:#fff;padding:12px 18px;font-weight:900;font-size:15px;cursor:pointer}.send:disabled{opacity:.4;cursor:not-allowed}.result{grid-column:1/-1;display:none;padding:10px 12px;border-radius:7px;background:#0b1420;border:1px solid var(--line);white-space:pre-wrap;word-break:break-word}.result.show{display:block}
@media(max-width:800px){.content{padding:10px}.form{grid-template-columns:1fr}.field,.field.wide,.field.full{grid-column:auto}.advanced{grid-template-columns:1fr 1fr}.send{width:100%;margin-left:0}.actions{flex-direction:column;align-items:stretch}.button-group .toggle-btn{flex:1 1 calc(50% - 5px)}}
@media(max-width:480px){.advanced{grid-template-columns:1fr}.brand{align-items:flex-start;flex-direction:column}}
</style>
</head>
<body>
<header><div class="brand"><h1>A18_2</h1><nav class="tabs" aria-label="A18_2 頁面"><a href="/swing">完整操作</a><a href="/simple" class="active" aria-current="page">精簡操作</a></nav></div></header>
<main class="content">
<section class="card">
  <div class="card-head"><h2>精簡真單操作</h2><span id="runtimeBadge" class="badge warn">A18_21 檢查中</span><span id="controlBadge" class="badge warn">交易控制檢查中</span></div>
  <div class="form">
    <div class="field wide"><label for="symbol">股票代號</label><div class="symbol-wrap"><input id="symbol" list="symbolList" maxlength="12" autocomplete="off" placeholder="例如 2330"><datalist id="symbolList"></datalist><span id="company" class="company">—</span></div></div>
    <div class="field"><span class="group-title">方向</span><div id="directionGroup" class="button-group direction"><button type="button" class="toggle-btn active" data-value="LONG">LONG 多單</button><button type="button" class="toggle-btn" data-value="SHORT">SHORT 空單</button></div></div>
    <div class="field"><label for="quantity">股數</label><input id="quantity" type="number" min="1" step="1" value="1000"></div>
    <div class="field"><label for="stopPct">固定停損 %</label><input id="stopPct" type="number" min="0" step="0.1" value="1"></div>
    <div class="field"><label for="trailPct">移動停利 %</label><input id="trailPct" type="number" min="0" step="0.1" value="1.5"></div>
    <div class="field"><span class="group-title">成本保本</span><div class="switch-row"><label class="switch"><input id="breakEven" type="checkbox" checked><span class="slider"></span></label><strong id="breakEvenText">啟用</strong></div></div>
    <div class="field"><label for="breakEvenTrigger">保本啟動 %</label><input id="breakEvenTrigger" type="number" min="0" step="0.1" value="1"></div>

    <div class="field full"><span class="group-title">移動停利模式</span><div id="modeGroup" class="button-group"><button type="button" class="toggle-btn active" data-value="FIXED">固定%</button><button type="button" class="toggle-btn" data-value="ATR">ATR動態</button><button type="button" class="toggle-btn" data-value="MAX_FIXED_ATR">固定/ATR取大</button><button type="button" class="toggle-btn" data-value="SIGMA">標準差σ</button><button type="button" class="toggle-btn" data-value="REBOUND_QUANTILE">反彈分位</button></div></div>
    <div class="field full"><span class="group-title">移動停利確認</span><div id="confirmationGroup" class="button-group"><button type="button" class="toggle-btn active" data-value="NONE">不確認</button><button type="button" class="toggle-btn" data-value="VOLUME">放量</button><button type="button" class="toggle-btn" data-value="STRUCTURE">結構突破</button><button type="button" class="toggle-btn" data-value="VOLUME_OR_STRUCTURE">放量或結構</button></div></div>
    <div class="field wide"><label for="confirmationFill">確認成交</label><select id="confirmationFill"><option value="BAR_CLOSE">確認K收盤</option><option value="CONFIRM_TOUCH">確認觸發價（實驗）</option></select><small style="color:var(--warn)">此項同步完整操作的歷史試算設定；REAL 真單為確認成立後送出實際委託，不以此欄保證成交價。</small></div>

    <details id="advancedParams"><summary>進階參數（平常可不調整）</summary><div class="advanced">
      <div class="field"><label for="sourceInterval">動態來源週期</label><select id="sourceInterval"><option value="1">1秒</option><option value="5">5秒</option><option value="15">15秒</option><option value="30">30秒</option><option value="60">60秒</option></select></div>
      <div class="field"><label for="lookback">回看 K</label><input id="lookback" type="number" min="2" max="500" value="20"></div>
      <div class="field"><label for="multiplier">倍數</label><input id="multiplier" type="number" min="0" step="0.1" value="1.5"></div>
      <div class="field"><label for="quantile">分位 %</label><input id="quantile" type="number" min="0" max="100" step="1" value="80"></div>
      <div class="field"><label for="volumeMultiplier">量倍</label><input id="volumeMultiplier" type="number" min="0" step="0.1" value="1.5"></div>
    </div></details>

    <div id="eligibility" class="status blocked">正在確認是否可送出真單。</div>
    <div class="actions"><span style="color:var(--warn);font-size:12px">送出後會建立 A18_21 ImmediateMarket REAL 進場計畫。</span><button id="send" class="send" type="button" disabled>送出真單</button></div>
    <div id="result" class="result"></div>
  </div>
</section>
</main>
<script>
(()=>{'use strict';
const $=id=>document.getElementById(id);let prefs={},names={},runtime=null,control=null,entries=[],reachable=false,entriesReachable=false,busy=false;let direction='LONG',mode='FIXED',confirmation='NONE';
const modeMap={FIXED:'Fixed',ATR:'Atr',MAX_FIXED_ATR:'MaxFixedAtr',SIGMA:'Sigma',REBOUND_QUANTILE:'ReboundQuantile'},confirmMap={NONE:'None',VOLUME:'Volume',STRUCTURE:'Structure',VOLUME_OR_STRUCTURE:'VolumeOrStructure'};
const clamp=(v,min,max,fallback)=>{v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback};
async function json(url,options){const r=await fetch(url,{cache:'no-store',...options});let body=null;try{body=await r.json()}catch{body={error:`HTTP ${r.status}`}}if(!r.ok)throw new Error(body?.error||body?.title||`HTTP ${r.status}`);return body}
function setGroup(id,value){const group=$(id);for(const b of group.querySelectorAll('.toggle-btn'))b.classList.toggle('active',b.dataset.value===value)}
function selectedSymbol(){return $('symbol').value.trim().toUpperCase()}
function updateCompany(){const s=selectedSymbol();$('company').textContent=names[s]||'—'}
function openPlan(){const s=selectedSymbol();return entries.find(p=>String(p?.symbol||p?.symbolOrName||'').trim().toUpperCase()===s&&['pending','submitted'].includes(String(p?.status||'').toLowerCase()))}
function setBadges(){const h=$('runtimeBadge'),c=$('controlBadge');if(!reachable){h.textContent='A18_21 無法連線';h.className='badge bad'}else{const real=runtime?.brokerProvider==='Yuanta'&&runtime?.enableBrokerExecution===true&&runtime?.enableRealOrders===true,account=runtime?.accountRefreshHealthy===true;h.textContent=account?`A18_21 ${runtime?.status||'OK'} · ${real?'REAL 已啟用':'REAL 未啟用'}`:`A18_21 ${runtime?.status||'DEGRADED'} · 帳務不可用`;h.className=`badge ${account?(real?'ok':'warn'):'bad'}`}if(!control){c.textContent='交易控制未知';c.className='badge bad'}else if(control.blocked){c.textContent='交易已封鎖';c.className='badge bad'}else{c.textContent='交易控制未封鎖';c.className='badge ok'}}
function eligibility(){let ok=true,reason='可送出：將以目前設定建立 ImmediateMarket 真單進場計畫。';const s=selectedSymbol(),qty=Number($('quantity').value),src=Number($('sourceInterval').value),advanced=mode!=='FIXED'||confirmation!=='NONE'||src!==1,supported=Array.isArray(runtime?.trailingSourceIntervalsSeconds)?runtime.trailingSourceIntervalsSeconds.map(Number):[];if(!s){ok=false;reason='請輸入股票代號。'}else if(Object.keys(names).length&& !names[s]){ok=false;reason='股票代號不在目前商品清單中。'}else if(!Number.isInteger(qty)||qty<=0){ok=false;reason='股數必須是大於 0 的整數。'}else if(!reachable){ok=false;reason='A18_21 健康或交易控制狀態無法取得，禁止送單。'}else if(runtime?.accountRefreshHealthy!==true){ok=false;reason=`A18_21 券商帳務 refresh 不健康，禁止送真單${runtime?.accountRefreshLastError?`：${runtime.accountRefreshLastError}`:''}。`}else if(!entriesReachable){ok=false;reason='A18_21 計畫歷史無法取得，為避免重複送單目前禁止建立新計畫。'}else if(advanced&&runtime?.advancedTrailing!==true){ok=false;reason='A18_21 未宣告 advancedTrailing capability，禁止送出進階移動停利真單。'}else if(src!==1&&!supported.includes(src)){ok=false;reason=`A18_21 未宣告支援 ${src} 秒移動停利來源週期。`}else if(!(runtime?.brokerProvider==='Yuanta'&&runtime?.enableBrokerExecution===true&&runtime?.enableRealOrders===true)){ok=false;reason='A18_21 目前不是 Yuanta REAL 可執行狀態。'}else if(control?.blocked){ok=false;reason='A18_21 kill-switch／交易控制目前封鎖。'}else if(openPlan()){ok=false;reason=`此股票仍有 ${openPlan().status} 計畫 ${openPlan().id}，禁止重複送單。`}const e=$('eligibility');e.textContent=reason;e.className=`status ${ok?'ready':'blocked'}`;$('send').disabled=!ok||busy;return ok}
function payload(){const feeRate=clamp(prefs.simFeeRate,0,100,.0855),taxMode=['DAYTRADE','NORMAL'].includes(prefs.simTaxMode)?prefs.simTaxMode:'DAYTRADE';return{symbolOrName:selectedSymbol(),direction:direction==='LONG'?'Long':'Short',quantityShares:Number($('quantity').value),entry:{type:'ImmediateMarket',triggerPrice:0,triggerDirection:'AtOrBelow'},exitRules:{fixedForceExit:{enabled:false,price:0},adverseStopLoss:{enabled:Number($('stopPct').value)>0,percent:clamp($('stopPct').value,0,50,0)},positionLossStop:{enabled:false,amountTwd:0},trailingExit:{enabled:Number($('trailPct').value)>0,percent:clamp($('trailPct').value,0,50,0),mode:modeMap[mode]||'Fixed',sourceIntervalSeconds:Number($('sourceInterval').value),lookback:Math.trunc(clamp($('lookback').value,2,500,20)),multiplier:clamp($('multiplier').value,0,100,1.5),quantile:clamp($('quantile').value,0,100,80),confirmation:confirmMap[confirmation]||'None',volumeMultiplier:clamp($('volumeMultiplier').value,0,100,1.5),breakEvenEnabled:$('breakEven').checked,breakEvenTriggerPercent:clamp($('breakEvenTrigger').value,0,50,1),breakEvenOffsetPercent:Math.max(0,2*feeRate+(taxMode==='DAYTRADE'?.15:.3))},periodicTrade:{enabled:false,action:'Buy',intervalSeconds:60,quantity:0},forcedExitTime:{enabled:false,time:'00:00:00'},adverseStepTrade:{enabled:false,everyTwd:0,quantity:0,mode:'Add'}},exitTradingBudgetTwd:0,note:'source=A18_2 simple operation'}}
async function savePrefs(){const merged={...prefs,symbol:selectedSymbol(),simDirection:direction,simQuantity:Math.max(1,Math.trunc(Number($('quantity').value)||1)),simStopPct:clamp($('stopPct').value,0,50,1),simTrailPct:clamp($('trailPct').value,0,50,1.5),simBreakEvenEnabled:$('breakEven').checked,simBreakEvenTriggerPct:clamp($('breakEvenTrigger').value,0,50,1),simTrailMode:mode,simSourceIntervalSeconds:Number($('sourceInterval').value),simLookback:Math.trunc(clamp($('lookback').value,2,500,20)),simMultiplier:clamp($('multiplier').value,0,100,1.5),simQuantile:clamp($('quantile').value,0,100,80),simConfirmation:confirmation,simConfirmationFillMode:$('confirmationFill').value,simVolumeMultiplier:clamp($('volumeMultiplier').value,0,100,1.5)};try{prefs=await json('/api/swing/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(merged)})}catch{}}
async function poll(){try{const [h,c,e]=await Promise.allSettled([json('/api/runtime21/health'),json('/api/runtime21/trading-control'),json('/api/runtime21/entries')]);runtime=h.status==='fulfilled'?h.value:null;control=c.status==='fulfilled'?c.value:null;reachable=h.status==='fulfilled'&&c.status==='fulfilled';entriesReachable=e.status==='fulfilled'&&Array.isArray(e.value);if(entriesReachable)entries=e.value;setBadges();eligibility()}catch{reachable=false;setBadges();eligibility()}}
async function send(){if(!eligibility())return;const p=payload(),tr=p.exitRules.trailingExit,summary=`股票：${p.symbolOrName}${names[p.symbolOrName]?` ${names[p.symbolOrName]}`:''}\n方向：${p.direction}\n股數：${p.quantityShares}\n固定停損：${p.exitRules.adverseStopLoss.enabled?p.exitRules.adverseStopLoss.percent+'%':'停用'}\n移動停利：${tr.enabled?tr.percent+'% / '+tr.mode:'停用'}\n成本保本：${tr.breakEvenEnabled?'啟用 @ +'+tr.breakEvenTriggerPercent+'%':'停用'}\n移動停利確認：${tr.confirmation}\n\n這會送出 REAL 真實委託。`;if(!confirm(summary+'\n\n確定送出？'))return;busy=true;eligibility();$('result').className='result show';$('result').textContent='送單中…';try{await savePrefs();const row=await json('/api/runtime21/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});$('result').textContent=`已建立真單計畫\nPlan ID：${row.id||'—'}\n狀態：${row.status||'—'}`;await poll()}catch(e){$('result').textContent=`建立真單計畫失敗：${e.message}`}finally{busy=false;eligibility()}}
function wireGroup(id,onchange){$(id).addEventListener('click',e=>{const b=e.target.closest('.toggle-btn');if(!b)return;onchange(b.dataset.value);setGroup(id,b.dataset.value);savePrefs();eligibility()})}
async function init(){try{const [p,n]=await Promise.all([json('/api/swing/state'),json('/api/symbols/names')]);prefs=p;names=n||{}}catch{}$('symbol').value=prefs.symbol||'';direction=['LONG','SHORT'].includes(prefs.simDirection)?prefs.simDirection:'LONG';mode=['FIXED','ATR','MAX_FIXED_ATR','SIGMA','REBOUND_QUANTILE'].includes(prefs.simTrailMode)?prefs.simTrailMode:'FIXED';confirmation=['NONE','VOLUME','STRUCTURE','VOLUME_OR_STRUCTURE'].includes(prefs.simConfirmation)?prefs.simConfirmation:'NONE';$('quantity').value=Number.isFinite(+prefs.simQuantity)?Math.max(1,Math.trunc(+prefs.simQuantity)):1000;$('stopPct').value=Number.isFinite(+prefs.simStopPct)?+prefs.simStopPct:1;$('trailPct').value=Number.isFinite(+prefs.simTrailPct)?+prefs.simTrailPct:1.5;$('breakEven').checked=prefs.simBreakEvenEnabled!==false;$('breakEvenTrigger').value=Number.isFinite(+prefs.simBreakEvenTriggerPct)?+prefs.simBreakEvenTriggerPct:1;$('sourceInterval').value=[1,5,15,30,60].includes(+prefs.simSourceIntervalSeconds)?String(+prefs.simSourceIntervalSeconds):'1';$('lookback').value=Number.isFinite(+prefs.simLookback)?+prefs.simLookback:20;$('multiplier').value=Number.isFinite(+prefs.simMultiplier)?+prefs.simMultiplier:1.5;$('quantile').value=Number.isFinite(+prefs.simQuantile)?+prefs.simQuantile:80;$('volumeMultiplier').value=Number.isFinite(+prefs.simVolumeMultiplier)?+prefs.simVolumeMultiplier:1.5;$('confirmationFill').value=['BAR_CLOSE','CONFIRM_TOUCH'].includes(prefs.simConfirmationFillMode)?prefs.simConfirmationFillMode:'BAR_CLOSE';setGroup('directionGroup',direction);setGroup('modeGroup',mode);setGroup('confirmationGroup',confirmation);$('breakEvenText').textContent=$('breakEven').checked?'啟用':'停用';$('breakEvenTrigger').disabled=!$('breakEven').checked;$('confirmationFill').disabled=confirmation==='NONE';$('symbolList').innerHTML=Object.entries(names).map(([s,n])=>`<option value="${s}">${n}</option>`).join('');updateCompany();wireGroup('directionGroup',v=>direction=v);wireGroup('modeGroup',v=>mode=v);wireGroup('confirmationGroup',v=>{confirmation=v;$('confirmationFill').disabled=v==='NONE'});for(const id of ['symbol','quantity','stopPct','trailPct','breakEvenTrigger','sourceInterval','lookback','multiplier','quantile','volumeMultiplier','confirmationFill'])$(id).addEventListener('change',()=>{if(id==='symbol')updateCompany();savePrefs();eligibility()});$('symbol').addEventListener('input',()=>{updateCompany();eligibility()});$('breakEven').addEventListener('change',()=>{$('breakEvenText').textContent=$('breakEven').checked?'啟用':'停用';$('breakEvenTrigger').disabled=!$('breakEven').checked;savePrefs();eligibility()});$('send').addEventListener('click',send);await poll();setInterval(poll,2000)}
init();})();
</script>
</body>
</html>
""";
}
