using System.Text.Json;
namespace A18.Realtime.Api;
internal sealed record SwingBrowseState(string Symbol="2330", string Date="", string Interval="5", bool Overlay=false, bool MultiDay=false, int LookbackDays=1, string Group="", bool ShowSectionNumbers=true, bool AutoStrategyA=false, bool AutoStrategyB=false, decimal AutoAStopPct=1m, decimal AutoATrailPct=0.5m, decimal AutoBStopPct=0.7m, decimal AutoBTrailPct=1m, string AutoATrailMode="FIXED", int AutoASourceIntervalSeconds=1, int AutoALookback=20, decimal AutoAMultiplier=1.5m, decimal AutoAQuantile=80m, string AutoAConfirmation="NONE", decimal AutoAVolumeMultiplier=1.5m, string AutoBTrailMode="FIXED", int AutoBSourceIntervalSeconds=1, int AutoBLookback=20, decimal AutoBMultiplier=1.5m, decimal AutoBQuantile=80m, string AutoBConfirmation="NONE", decimal AutoBVolumeMultiplier=1.5m, string SimDirection="LONG", int SimQuantity=1000, string SimTaxMode="DAYTRADE", decimal SimFeeRate=0.0855m, decimal SimMinFee=20m, decimal SimStopPct=1m, decimal SimTrailPct=1.5m, string SimTrailMode="FIXED", int SimSourceIntervalSeconds=1, int SimLookback=20, decimal SimMultiplier=1.5m, decimal SimQuantile=80m, string SimConfirmation="NONE", decimal SimVolumeMultiplier=1.5m, bool ImpulseEnabled=false, string ImpulseVersion="V1", bool FoldGroupNav=true, bool FoldSummary=true, bool FoldTargetSwitch=true, bool FoldStrategyLong=true, bool FoldStrategyShort=true, bool FoldManualSim=true, bool FoldDiagnostic=true, bool FoldAnnotation=true, bool HeaderPinned=false, string HeaderMode="AUTO");
internal sealed class SwingState(IConfiguration config)
{
    private readonly string _path=config["Swing:StatePath"]??"/data/reference/swing-state.json"; private readonly object _gate=new();
    public SwingBrowseState Read(){lock(_gate){if(!File.Exists(_path))return new();try{return JsonSerializer.Deserialize<SwingBrowseState>(File.ReadAllText(_path),new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??new();}catch{return new();}}}
    public SwingBrowseState Save(SwingBrowseState s){lock(_gate){var modes=new[]{"FIXED","ATR","MAX_FIXED_ATR","SIGMA","REBOUND_QUANTILE"};var confirms=new[]{"NONE","VOLUME","STRUCTURE","VOLUME_OR_STRUCTURE"};var sourceIntervals=new[]{1,5,15,30,60};var clean=s with{HeaderMode=new[]{"AUTO","PINNED","STATIC"}.Contains(s.HeaderMode)?s.HeaderMode:(s.HeaderPinned?"PINNED":"AUTO"),HeaderPinned=(new[]{"AUTO","PINNED","STATIC"}.Contains(s.HeaderMode)?s.HeaderMode:(s.HeaderPinned?"PINNED":"AUTO"))=="PINNED",Symbol=(s.Symbol??"2330").Trim().ToUpperInvariant(),Interval=new[]{"1","5","60","300"}.Contains(s.Interval)?s.Interval:"5",LookbackDays=Math.Clamp(s.LookbackDays,1,20),Group=(s.Group??"").Trim(),AutoAStopPct=Math.Clamp(s.AutoAStopPct,0m,50m),AutoATrailPct=Math.Clamp(s.AutoATrailPct,0m,50m),AutoBStopPct=Math.Clamp(s.AutoBStopPct,0m,50m),AutoBTrailPct=Math.Clamp(s.AutoBTrailPct,0m,50m),AutoATrailMode=modes.Contains(s.AutoATrailMode)?s.AutoATrailMode:"FIXED",AutoASourceIntervalSeconds=sourceIntervals.Contains(s.AutoASourceIntervalSeconds)?s.AutoASourceIntervalSeconds:1,AutoALookback=Math.Clamp(s.AutoALookback,2,500),AutoAMultiplier=Math.Clamp(s.AutoAMultiplier,0m,100m),AutoAQuantile=Math.Clamp(s.AutoAQuantile,0m,100m),AutoAConfirmation=confirms.Contains(s.AutoAConfirmation)?s.AutoAConfirmation:"NONE",AutoAVolumeMultiplier=Math.Clamp(s.AutoAVolumeMultiplier,0m,100m),AutoBTrailMode=modes.Contains(s.AutoBTrailMode)?s.AutoBTrailMode:"FIXED",AutoBSourceIntervalSeconds=sourceIntervals.Contains(s.AutoBSourceIntervalSeconds)?s.AutoBSourceIntervalSeconds:1,AutoBLookback=Math.Clamp(s.AutoBLookback,2,500),AutoBMultiplier=Math.Clamp(s.AutoBMultiplier,0m,100m),AutoBQuantile=Math.Clamp(s.AutoBQuantile,0m,100m),AutoBConfirmation=confirms.Contains(s.AutoBConfirmation)?s.AutoBConfirmation:"NONE",AutoBVolumeMultiplier=Math.Clamp(s.AutoBVolumeMultiplier,0m,100m),SimDirection=new[]{"LONG","SHORT"}.Contains(s.SimDirection)?s.SimDirection:"LONG",SimQuantity=Math.Clamp(s.SimQuantity,1,10000000),SimTaxMode=new[]{"DAYTRADE","NORMAL"}.Contains(s.SimTaxMode)?s.SimTaxMode:"DAYTRADE",SimFeeRate=Math.Clamp(s.SimFeeRate,0m,100m),SimMinFee=Math.Clamp(s.SimMinFee,0m,1000000m),SimStopPct=Math.Clamp(s.SimStopPct,0m,50m),SimTrailPct=Math.Clamp(s.SimTrailPct,0m,50m),SimTrailMode=modes.Contains(s.SimTrailMode)?s.SimTrailMode:"FIXED",SimSourceIntervalSeconds=sourceIntervals.Contains(s.SimSourceIntervalSeconds)?s.SimSourceIntervalSeconds:1,SimLookback=Math.Clamp(s.SimLookback,2,500),SimMultiplier=Math.Clamp(s.SimMultiplier,0m,100m),SimQuantile=Math.Clamp(s.SimQuantile,0m,100m),SimConfirmation=confirms.Contains(s.SimConfirmation)?s.SimConfirmation:"NONE",SimVolumeMultiplier=Math.Clamp(s.SimVolumeMultiplier,0m,100m)};Directory.CreateDirectory(Path.GetDirectoryName(_path)!);var tmp=_path+".tmp";File.WriteAllText(tmp,JsonSerializer.Serialize(clean,new JsonSerializerOptions{WriteIndented=true}));File.Move(tmp,_path,true);return clean;}}
}
